### ISSUE TITLE
Baseline solution

### ISSUE THREAD

**Issue by azhe825** [azhe825/CSC510#15]
@imaginationsuper @amritbhanu @dichen001 
What is the baseline solution (supervised learning classifier)? K-NN? Naive Bayse? or SVM?

**Comment by amritbhanu** [comment]
Baseline should be supervised learning, with either of the learners. I think different classifiers will better the different performance metrics.

**Comment by azhe825** [comment]
I will use both K-NN and SVM since the implementation of semi-supervised learning for these two can be different.

**Comment by jerry-shijieli** [comment]
I remember the baseline is simply using the preprocessed feature data as the bag-of-word and annotate the email with existing labels. Is that what we discuss before?

**Comment by azhe825** [comment]
After that, choose a classifier to finish all the process. Your result will act as the baseline result, for us to compare with.
