### ISSUE TITLE
Data sets ready?

### ISSUE THREAD

**Issue by azhe825** [azhe825/CSC510#18]
Do we already have a cleaned and well-structured data set?

**Comment by jerry-shijieli** [comment]
For the cleaned data, does that mean remove all the all_document folders and any folder that has less than 10 emails?

**Comment by jerry-shijieli** [comment]
What kind of structured data does the testing method need? We only have words from subject and body.

**Comment by azhe825** [comment]
several txt or csv files, each contains emails received by one person.
Inside each txt, each line is one email (subject+body, labeled as the folder name, separate label with content by some unique symbol).

Yes, remove folders that has less than 10 emails.
