### ISSUE TITLE
We need a small demo on March 1st?

### ISSUE THREAD

**Issue by azhe825** [azhe825/CSC510#20]
https://piazza.com/class?cid=il02b2rid9j368&nid=iizdroc9bwn7b1&token=ScZFPXFgtim

Also need to decide a time for presentation. 10:00 Friday, March 4th ok for everyone?

**Comment by jerry-shijieli** [comment]
I am fine with the time and will reorganize my code tomorrow.

**Comment by amritbhanu** [comment]
That time works for me

**Comment by dichen001** [comment]
Work fine for me.

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=dchen20@ncsu.edu&idSignature=22

**Comment by azhe825** [comment]
Registered 10:00 am Friday.
