### ISSUE TITLE
Preprocessed Data

### ISSUE THREAD

**Issue by amritbhanu** [azhe825/CSC510#24]
@imaginationsuper Can you please remove the extra whitespaces (just keep 1 whitespace) from the dataset.txt file? So that it is easier to extract by our code.

**Comment by amritbhanu** [comment]
This code will do the job.

```
re.sub(r'\s+', ' ', "abc   xyz     lmn")+"\n")
abc xyz lmn
```

**Comment by jerry-shijieli** [comment]
Code updated. Use emailParserX.py to get dataset.txt and dataConversionF.py to convert to word vectors.

**Comment by jerry-shijieli** [comment]
The 'L' letter in wordVectors.txt means long int data type, which is produced by the scikit-learn tokenizer
