### ISSUE TITLE
Alternate featurization methed: word vector?

### ISSUE THREAD

**Issue by dichen001** [azhe825/CSC510#26]
When email represented as 3 words, can we map each word into a constant dimensionality of word vector. This way, each word will be uniquely identified. 

> "Hi,
> This is jack!"

```
'Hi'  --> [0,0,0,0,1]
'This' --> [0,0,0,1,0]
'is'--> [0.0.1.0.0]
'jack'--> [0,1,0,0,0]

```

@imaginationsuper  What's the word vector API you have talked before? Can we use that?

**Comment by jerry-shijieli** [comment]
This binary representation is still a sparse matrix(vector). To improve this, you can use the **gensim word2vec** to do this job. It uses a neural network to train the word and express each word using some weight factors.

**Comment by amritbhanu** [comment]
as I discussed with Jack about this method, jerry can we used this method to do the featurization? gensim can support this?

@azhe825 but even if we can represent the features in the above manner, can we use our scikit learner api to accept these as features?

**Comment by jerry-shijieli** [comment]
API and demos of gensim word2vec:
https://radimrehurek.com/gensim/models/word2vec.html
