### ISSUE TITLE
Word Vector performs badly when training set is only 10 emails....

### ISSUE THREAD

**Issue by dichen001** [azhe825/CSC510#30]

**Comment by azhe825** [comment]
Can u train on some knowledge base like google news, Wikipedia?

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io

**Comment by dichen001** [comment]
already tried that at [this commit](https://github.com/azhe825/CSC510/commit/2230b9fb1fa1b56381ae911d3ffeddf9fb0be7d1)
use a pre-trained model by Google news using 100 billion words. doesn't help much.

**Comment by dichen001** [comment]
I believe this is because simply add the word vector is not the right way.  One possible solution can be found in this [paper](http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7363382)

No time to try for this due. Maybe later.
