### ISSUE TITLE
Supervised Classification: #1:SVM  #2:KNN(k=10)  #3:DT finished.

### ISSUE THREAD

**Issue by dichen001** [azhe825/CSC510#31]
tested k = 5,10,15,20.   best when k = 10

**Comment by azhe825** [comment]
Readable results on all datasets?

**Comment by dichen001** [comment]
No. You have to use the load() in function.py to load the data.

**Comment by azhe825** [comment]
Can you make some figures showing the result, see #32 

Use F_M for the performance. See #33 

Run on all data sets if possible.

**Comment by dichen001** [comment]
# KNN:

![KNN](https://raw.githubusercontent.com/azhe825/CSC510/master/Results/semi_KNN_.png)

# DT

![MNB](https://raw.githubusercontent.com/azhe825/CSC510/master/Results/semi_DT_.png)

# SVM

![SVM](https://raw.githubusercontent.com/azhe825/CSC510/master/Results/semi_SVM_.png)

# Summery

![Summery](https://raw.githubusercontent.com/azhe825/CSC510/master/Results/semi_classifier.png)

![sum](https://raw.githubusercontent.com/azhe825/CSC510/master/Results/comp_classifier.png)

**Comment by azhe825** [comment]
Strange result with NB. Need to look into it.  SMOTE+NB causes sth wrong.

**Comment by dichen001** [comment]
@azhe825  removed NB. Cannot find out why.  Use DT instead, and it performs good.
