### ISSUE TITLE
Unsupervised Learning

### ISSUE THREAD

**Issue by amritbhanu** [azhe825/CSC510#32]
## Results with top 100 topics

![file](https://github.com/azhe825/CSC510/blob/master/Results/lda/lda_SVM_100.png?raw=true)
## Results with top 50 topics

![file](https://github.com/azhe825/CSC510/blob/master/Results/lda/lda_SVM_50.png?raw=true)
## Results with top 20 topics

![file](https://github.com/azhe825/CSC510/blob/master/Results/lda/lda_SVM_20.png?raw=true)

**Comment by amritbhanu** [comment]
Any more results needed to add onto this?

**Comment by azhe825** [comment]
How is the F score calculated here?

Why do we have some 0 median on some data sets?

**Comment by amritbhanu** [comment]
After doing the unsupervised learning, I get the words based on the top n topics. These words will form the basis of new corpus. Then a specific target label is chosen (positive label), and the rest is chosen as (negative label). I believe that specific label is a problem.

**Comment by azhe825** [comment]
Can u do it for a multi-classification form?  Just feed all the data and labels to the classifier.
U can use the evaluate function in func.py to calculate F_M score.
