### ISSUE TITLE
Apr 1 report

### ISSUE THREAD

**Issue by amritbhanu** [azhe825/CSC510#40]
Watch out for deliverables details on this [page](http://se16.unbox.org/project/apr1.md)

**Comment by azhe825** [comment]
Collected everything we can reuse from Feb report, basic structure is also defined.

Please see the temp pdf file [here](https://github.com/azhe825/CSC510/blob/master/report/April_temp.pdf)

Work on things you think can be done separately first. Discuss and combine things together tomorrow. Worried about if we can finish this report by tomorrow... Maybe should create a md file first.

**Comment by jerry-shijieli** [comment]
Could you also upload the latex file of this pdf?

**Comment by azhe825** [comment]
@imaginationsuper you can work on sharelatex, right now you are shared with it. It is the April.tex in CSC 510 in sharelatex.

**Comment by dichen001** [comment]
@azhe825  why can't I see that? Below are all I can see.
![image](https://cloud.githubusercontent.com/assets/15117843/14338107/22e20a2a-fc42-11e5-80ea-3978129d4e02.png)

**Comment by azhe825** [comment]
Cause u r not shared... Can only have one person shared at a time... It's the free version

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io

**Comment by jerry-shijieli** [comment]
I will work on it soon tonight and then you can share with others.

**Comment by dichen001** [comment]
Oh... Got it. Keep me updated.

**Comment by jerry-shijieli** [comment]
@azhe825 I just edited my part so far. Please shift the sharelatex to @dichen001

**Comment by azhe825** [comment]
@dichen001 you have the ball now

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io

**Comment by dichen001** [comment]
Got it. Thanks.

**Comment by dichen001** [comment]
hi @azhe825 , just finished the supervised part, you can pass the ball to @amritbhanu

**Comment by dichen001** [comment]
Hi @amritbhanu, cause I cannot share the original one to you. I shared my copy to you, so you can work on that, then merge with @azhe825 's version later.

**Comment by amritbhanu** [comment]
got a copy of the report from jack! Thanks

**Comment by amritbhanu** [comment]
jack, did you remove sharing of report? I still had to complete the GUI part

**Comment by dichen001** [comment]
sorry, just resend you the link.

**Comment by amritbhanu** [comment]
done jack! You can share this back with zhe. We can combine them now.

**Comment by amritbhanu** [comment]
@azhe825 
For unsupervised learning section, I made some changes in the wordings. Add this again. Images will remain the same.

```
\subsubsection{Unsupervised Learning}
% @Amritanshu
Unsupervised learning is the machine learning task of inferring a function to describe hidden structure from unlabeled data. There are various tools of doing unsupervised learning, and we used Latent Dirichlet allocation~\cite{blei2003latent}. We used LDA because of its useful importance and advantages for finding useful topics from an unlabeled data. LDA features were extracted and given as input to SVM learner. LDA is used as a feature extractor. We have already shown in Figure 4 that SVM performs better than the other classifiers.

The Famous Enron email dataset is used and have already specified about the pre-processing steps and its final structure above. We tested the data on 7 different users. There are different labels already defined for the mails. We selected 5 top labels for each user dataset, and converted it into a binary classifier where those 5 labels are given "YES" label and others as "NO" label. And we also selected different ranges of cluster size namely 20, 50 and 100. Respective results can be seen for all the different cluster size given below.

    \begin{figure}[t]
      \includegraphics[width=\linewidth]{./fig/lda_SVM_20.png}
      \caption{Performance of LDA with 12 clusters}
      \label{fig: comp among users}
    \end{figure}

    \begin{figure}[t]
      \includegraphics[width=\linewidth]{./fig/lda_SVM_50.png}
      \caption{Performance of LDA with 50 clusters}
      \label{fig: comp incrementally}
    \end{figure}

    \begin{figure}[t]
      \includegraphics[width=\linewidth]{./fig/lda_SVM_100.png}
      \caption{Performance of LDA with 100 clusters}
      \label{fig: comp among users}
    \end{figure}


Following results show highly instability of F-Score across different datasets. The reason for that is, if we have large data for positive class then it gets you good results but if number of negative labels dominant over positive labels, it performs poorly. The other problem which we saw, the instability of these clusters even if there was no changes in the data or the parameters of the algorithm. These results made us to not use unsupervised features to train a classifier.
```

**Comment by amritbhanu** [comment]
for GUI Part,
Copy the image from https://github.com/azhe825/CSC510/blob/master/GUI/FinalPic.png

```
\subsection{GUI Development}
% @Amritanshu

The GUI is developed using Python Tkinter package. We took Gmail as our sample for making the Mailbox GUI. See Figure 9 for our mailbox interface. 

    \begin{figure}[t]
      \includegraphics[width=\linewidth]{./fig/FinalPic.png}
      \caption{Graphical User Interface}
      \label{fig: comp among users}
    \end{figure}

We have provided users with read mails, move mails to different folders, creation of user defined folders. We have also provided the user with different features to select on demand. These features are Implicit User Feedback, Explicit User Feedback, Multi-folders. 

The GUI is designed to not only load local email files for training classifier, but also read email from the online email account for different users. Under the hood, it will connect the server at preset frequency, fetch emails from the online account, categorize them using local classifier and refresh the emails saved on local folders. Currently, it support Gmail accounts only for security settings.
```

**Comment by azhe825** [comment]
ok

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io

**Comment by dichen001** [comment]
shared to @azhe825 now.

**Comment by dichen001** [comment]
make a new copy for the latest version of our report. Please check. @amritbhanu

**Comment by amritbhanu** [comment]
Just checked the report, and this looks good. I think we have covered most of the points which we wanted to convey
