### ISSUE TITLE
Project Presentation Date in April

### ISSUE THREAD

**Issue by jerry-shijieli** [azhe825/CSC510#45]
Check the registration link:
https://docs.google.com/spreadsheets/d/1SXVedXWhhpPkiVyrPAni-wF-B9hIr5xiYwsTCLMN58Q/edit#gid=0

**Comment by amritbhanu** [comment]
Time slot looks good

**Comment by dichen001** [comment]
Great.

**Comment by azhe825** [comment]
Fine with it.

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io
