### ISSUE TITLE
1st look of GUI

### ISSUE THREAD

**Issue by amritbhanu** [azhe825/CSC510#46]
Suggestions please?

![file](https://github.com/azhe825/CSC510/blob/master/GUI/1stlook.png?raw=true)

**Comment by jerry-shijieli** [comment]
How about aligning the buttons vertically in one column?

**Comment by amritbhanu** [comment]
More Suggestions?
- Someone pull the code and run the GUI/Gui.py code. Most of the buttons functionality is working. Just the "Move" button needs to be implemented.
- Structure of the file is : 

```
 label1 label2 label3 >>> Mail Body
```
- That file can be found in Mails/struct.txt

![file](https://github.com/azhe825/CSC510/blob/master/GUI/2ndlook.png?raw=true)

**Comment by dichen001** [comment]
Instead of having two box of Unread and Read, how about use the traditional email layout? Also, I think it would be better if you can put the buttons on the left to the above or bottom horizontally.(Just like a common email client :smile:

**Comment by azhe825** [comment]
What tool are you using?

**Comment by amritbhanu** [comment]
@dichen001 does the UI matter much? Because we got to stick with just basic functionalities.

@azhe825 Tkinter python package
