### ISSUE TITLE
Multi-label classification

### ISSUE THREAD

**Issue by azhe825** [azhe825/CSC510#48]
Motivation: in case of missing important emails, each email can appear in multiple folders. 

Solution: multi-label classification. Each folder has an independent classifier which predicts probability. If the probability exceeds a certain threshold,  email will appear in that folder.

Possible problems: 1. choose the thresholds 2. data logic in GUI should allow this change.

**Comment by dichen001** [comment]
Use one multi-class classifier, or use multiple binary classifiers?  Wouldn't the first be better? What's your opinion? @azhe825

**Comment by azhe825** [comment]
It is the first option that are utilized in our current code.

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io
