### ISSUE TITLE
Explicit user feedback

### ISSUE THREAD

**Issue by azhe825** [azhe825/CSC510#49]
Motivation: inspired by active learning.

Solution: Emails that do not pass any of the threshold (See #48) will appear in a specific pre-defined folder called Uncertain which requires the user to decide the correct folder the emails should go to.

Comments: not much work to do. Please work with @dichen001 on #48 and #49, these two are strongly connected.

**Comment by jerry-shijieli** [comment]
Ok, and I am also considering to build the GUI on a webpage using HTML and JS in the pattern of MVC. It will share the same data and results with that of @amritbhanu but facilitates the web and mobile use. Just basic functions to show our workflow are enough. And also it may be easier to convert web code to a mobile app using [PhoneGap](http://phonegap.com/getstarted/) if time permits.

**Comment by azhe825** [comment]
Great! But don't be too ambitious... Focus on webpage based first.
