### ISSUE TITLE
PUTGS

### ISSUE THREAD

**Issue by amritbhanu** [azhe825/CSC510#5]
the pattern (P) of errors for user group "U" using some software tool "T" to achieve some goal "G" and its solutions (S).

**Comment by azhe825** [comment]
- P: not all email folders are content-aware. Other types are time-aware like Machine Learning Course _ Spring 2014, and participant-aware like adviser. Use one single feature set or one single model to classify a mixture of these three types of emails can be misleading. **Supported by Alecsa: Attentive Learning for Email Categorization using Structural Aspects**
- U: especially for email users who receive hundreds of emails everyday. (for our project)
- T: email client, perhaps with some plugins.
- G: automatically classify incoming emails into different folders predefined by users.
- S: different models with different feature set, then do decision fusion.

**Comment by azhe825** [comment]
- P: users do not want to make to much effort on providing training set. Can only require dozens of examples in each folder. **Literature Review Required**
- U: especially for email users who receive hundreds of emails everyday. (for our project)
- T: email client, perhaps with some plugins.
- G: automatically classify incoming emails into different folders predefined by users.
- S: 1. incremental learning needed, model will keep training itself as new email comes. Active learning, can have a folder to ask user to manually classify the most confusing email. 2. have at least two  types of incremental models, one values more on the initial training set, one values more on the upcoming emails, have some rule to decide which one dominates. This structure can be more robust.

**Comment by jerry-shijieli** [comment]
# PUTGS

### P:

Email categorizations depends on specific user behaviors, while not all users will provide explicit feedback to the correctness of email labels.

### U:

For users who receive huge amount of emails daily in vastly diverse topics. And not all of those emails are necessary to read in details or make a reply.

### T:
- Email client receiving real-time email streams.
- Plugins to monitor user behaviors in the email client to provide implicit user feedback.
- API to access real-time email streams.

### G:

Automatically categorize the coming emails into user customized folders. 

### S:
- Email feature extraction in both formats and contents, i.e. keywords summary, sender address, subject topics, time and event detection. Optional features from reply, signature and attachment.
- Ensemble classifier using ANN and Decision Tree.

**Comment by dichen001** [comment]
From the [project page](http://se16.unbox.org/project/feb1.md). 

> Document some **problem** "P" with some **user group** "U" using some **software tool** "T" to achieve some **goal** "G".

## P: Problem
1. Email users have the tendency to tag their emails into different tags according to the functional differences of emails, such as Urgent, Importan, To-Do, Reminder, Data, Work, Private, ect.
2. However, they don't usually follow a strict pattern or logic for tagging their emails.
3. Their tagging logi may vary as time goes by.
4. Different users may have totally different way for taging their emails.
5. Nowadays, there is no such service like automatic tagging according to the users' previews tagging records.

## U: User
- Email heavy users: businessman, layers, managers, professors, ect.

## T: Software Tool
- Web-based email services. 
- Mobile email applications.

## G: Goal
- Provide the automatic tagging service for user emails base on their previous tag records.

## S: Solusion
- Build up a email applications that can load all the users email on other email accounts.
- Extact user-specific features from their emails that have already been tagged.
- Use these features to train classifiers.
- Put the new comming emails into different tags, and show that in the user interface.

**Comment by azhe825** [comment]
@dichen001 The problem and solution you describe here should not be in the scale of whole project. Right now you are describing the general problem and the general solution. Just specific one problem that we have not seen yet.

**Comment by azhe825** [comment]
- P: users definitely do not want to miss one single import email. Recall values more than precision. **Literature Review Required**
- U: especially for email users who receive hundreds of emails everyday. (for our project)
- T: email client, perhaps with some plugins.
- G: automatically classify incoming emails into different folders predefined by users.
- S: 1. on classifiers, we can address more weight on recall over precision by lowering the threshold; 2. can have one email assigned with multi-labels, it will appear in different folders.

**Comment by amritbhanu** [comment]
- P: Many of the user events are not captured properly when using an email system, which can provide good amount of information about those emails. Supported by - **Improving Automated Email Tagging with Implicit Feedback**
- U: Email users whose mailboxes are flooded with unimportant and important mails (for our project).
- T: Plugin like EP2 for MS OUTLOOK
- G: Make use of these implicit feedback events for better classification of mails into specific labels.
- S: Consider implicit events like saving an attachment, replying an email, forwarding, etc. Keep a threshold to identify the important mails once it exceeds the threshold limit. Various methods on implicit feedback can be used.

**Comment by dichen001** [comment]
I will take this one. :smile: 
- P: Most of the email user have the need to categorize their emails into different folders. However, nearly all the email services only offer passive folder-categorization, which means they only put emails into folders when users think of doing this. Besides, none of the exisiting email systems offer the automatic categorization function.
- U: Email heavy users.
- T: An email application.
- G: Build a email application and integrate the automatic and active email categorization. 
  - 'Active' and 'automatic' means it will put every new email into one preset folder from day one. Then, it will let users choose if it meet their expectation, or they can put them into other preset folders or create new folder by themself.
  - For 'automatic', it means it will classify the emails automatically. At first, it is based on the common features of the email categorization, then it will be customized for each user based on their previous email folder record.

**Comment by azhe825** [comment]
It is the whole service our project provides, you need to state a problem that we may face in order to achieve this goal. In a word, you need to change to another topic. The one you just describe will go into the introduction part of our report.

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io

**Comment by dichen001** [comment]
The **Problem** is existing service is passive categorization. 
The **Goal** is to make it active, automatic and smart.
The **Solution** is to categorize every email by default, and actively ask them for feedback.  The implementation is to add an interface level interaction with the user, so that we can put their email into the right folder. My focus here is the new interaction with user for email services, not the training algorithms.
