### ISSUE TITLE
GUI modification

### ISSUE THREAD

**Issue by azhe825** [azhe825/CSC510#50]
See #47 #48 #49, make changes to allow and facilitate all these features.

**Comment by azhe825** [comment]
@amritbhanu Need your help to combine code with GUI. When are you available? Better in the lab.

**Comment by amritbhanu** [comment]
Yes i will be available between 12 - 4.

**Comment by azhe825** [comment]
I may be in the lab after 3pm

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io
