### ISSUE TITLE
Availability?

### ISSUE THREAD

**Issue by amritbhanu** [azhe825/CSC510#54]
What is the suitable time for everyone to meet in the lab sometime tomorrow between 12 to 4?

I am available all the time between the above.

**Comment by dichen001** [comment]
After 2pm, then I will be free.

**Comment by jerry-shijieli** [comment]
I am available for all time interval. Thanks!

**Comment by azhe825** [comment]
anytime

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io

**Comment by amritbhanu** [comment]
Jerry, we can meet around now itself. And jack can join us later.
