### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by amritbhanu** [azhe825/CSC510#55]
https://github.com/azhe825/CSC510/blob/master/GUI/Gui.py#L368

Error thrown is at the above line: 

```
 File "/home/amrit/NCSU STUDY/Spring 16/CSC 510/CSC510/GUI/Gui.py", line 342, in check_credit
    for label in my_folder.classifier.classes_:
AttributeError: 'list' object has no attribute 'classes_'
```

**Comment by azhe825** [comment]
fixed that

**Comment by azhe825** [comment]
@amritbhanu Need your help on GUI, can you come to the lab tomorrow?

**Comment by amritbhanu** [comment]
Will you be in lab after 5 today? I will come back.
Else if it is possible we can discuss over hangouts for those problems.

**Comment by azhe825** [comment]
Sure, then tomorrow with hangout. Are you available around 10am?

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io

**Comment by amritbhanu** [comment]
yes talk to you at 10am

Amritanshu Agrawal
PhD Student
CS @ NC State
aagrawa8@ncsu.edu
http://amritag.wix.com/amrit http://ai4se.net/people/
