### ISSUE TITLE
Need a login pop-up window for general use

### ISSUE THREAD

**Issue by jerry-shijieli** [azhe825/CSC510#61]
We need one pop-up window to obtain user's loginID and password of Gmail account to test on real case and get feedback.  I will modify the emailReceiver.py into functions to insert into the GUI and use the new mail button for that function.

**Comment by jerry-shijieli** [comment]
@amritbhanu I have difficulty to link login pop-up window with the corresonding function, if you have time please check GUI5.py for that function. Also right button option was changed for mac interface, please check if it works for windows.

**Comment by amritbhanu** [comment]
right button option is working.
I will add that function

**Comment by amritbhanu** [comment]
@imaginationsuper i have updated the gui5. Please see the gmail login error. Once it works, we can see if its retrieving unread mails or not. and so on.
