### ISSUE TITLE
Preprocessing and basic solution

### ISSUE THREAD

**Issue by amritbhanu** [azhe825/CSC510#9]
This preprocessed data will be our training set for other solutions.
Enron dataset

**Comment by azhe825** [comment]
Sample code for preprocessing: 

https://github.com/ai-se/e-disc/blob/master/Datasets/Preprocess.py

https://github.com/ai-se/e-disc/blob/master/Datasets/formatData.py

https://github.com/ai-se/e-disc/blob/master/Zhe/winter/test_pre.py

**Comment by amritbhanu** [comment]
Zhe, other people wont be able to access them as it is a private repo.

**Comment by azhe825** [comment]
Only for Jerry

Best Regards,
Zhe,
Ph.D. scholar @ CS, NcState
http://azhe825.github.io

**Comment by jerry-shijieli** [comment]
I have uploaded my code for parsing each email into one-line entry with the seven largest email user data. The problem is that so far I could not save each data in each user's folder. I am continue working on this. But you can start to use it now. The _emailParserX.py_ is the latest version. The preprocessed data entry is in the following format:

User/Category  ::::::>>>>>>  words of subject + body

**Comment by dichen001** [comment]
@imaginationsuper  Just found that there is no delimiter between the subject and the body.
e.g. 

> /beck-s/2001_plan ::::::>>>>>>  Group ExpensesGuys attached you will find a final cut on the ENA  expense budget  ...

the subject is **Group Expenses**
the content is **Guys, attached ...**

Also, could we only keep the most related folder name, i.e. **2001_plan** instead of **/beck-s/2001_plan**, as the category?

**Comment by jerry-shijieli** [comment]
Yes, there are bugs in my code. You can parse and separate the user folder from the most related folder by the '/' character. I will also fix the delimiter after subject. Thanks! @dichen001

**Comment by azhe825** [comment]
https://github.com/ai-se/e-disc/blob/master/Zhe/02-24/src/topics.py

**Comment by jerry-shijieli** [comment]
Hi Guys, 

I updated the emailParserX.py code, which is used to collect all the email in the root folder and reorganize the email structure into the following format, in which (I suppose) each email takes one line:

/user_folder/category_folder/ ::::::>>>>>> email_subject_words *****\* email_body_words

I will perform word vector conversion using these data in another code script, which is still need some tuning.
